import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Sidebar } from "@/components/layout/SideBar";
import {
  ResizableHandle,
  ResizablePanel,
  ResizablePanelGroup,
} from "@/components/ui/resizable";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="h-screen flex flex-col">
          <header className="sticky top-0 z-10 flex flex-row justify-between items-center p-4 shadow-lg bg-gradient-to-r from-regal-blue">
            <Sidebar />
            <div className="flex-grow text-center">
              <h3 className="font-ppneuemachina text-3xl">HomeLab</h3>
            </div>
            <div className="w-0"></div>
          </header>
          <div className="overflow-y-auto">
            <div className="px-4 py-2">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
